CONDA_BUILD_SYSROOT:
  - /opt/MacOSX11.3.sdk  # [osx]

SDKROOT:
  - /opt/MacOSX11.3.sdk  # [osx]

MACOSX_DEPLOYMENT_TARGET:
  - 11.3                 # [osx]

target_platform:                                                                                                        
  - osx-arm64            # [osx]
  - osx-64               # [osx]
  - linux-aarch64        # [linux]
  - linux-64             # [linux]

c_compiler_version:
  - '>=15,<16'           # [linux]
  - '>=21,<22'           # [osx]

cxx_compiler_version:
  - '>=15,<16'           # [linux]
  - '>=21,<22'           # [osx]

clang_format:
  - '>=21,<22'

clangxx:
  - '>=21,<22'

libclang:
  - '>=21,<22'

python:
  - 3.12
  - 3.13
  - 3.14

fmt:
  - '>=12.1'

openssl:
  - '>=3.6'

libprotobuf:
   - '>=6.33'

# note!
#   https://anaconda.org/conda-forge/libarrow
#   https://github.com/conda-forge/arrow-cpp-feedstock/issues/1777#issuecomment-2978886239
libabseil:
   - '>=20250814.1'  # libprotobuf 6.33
